/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ConseilAdministrationRouteImport } from './routes/conseil-administration'
import { Route as CharteRouteImport } from './routes/charte'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilAdministrationRoute = ConseilAdministrationRouteImport.update({
  id: '/conseil-administration',
  path: '/conseil-administration',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteRoute = CharteRouteImport.update({
  id: '/charte',
  path: '/charte',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/conseil-administration': typeof ConseilAdministrationRoute
  '/partenaires': typeof PartenairesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/conseil-administration': typeof ConseilAdministrationRoute
  '/partenaires': typeof PartenairesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/conseil-administration': typeof ConseilAdministrationRoute
  '/partenaires': typeof PartenairesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/charte'
    | '/conseil-administration'
    | '/partenaires'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/charte' | '/conseil-administration' | '/partenaires'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/charte'
    | '/conseil-administration'
    | '/partenaires'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CharteRoute: typeof CharteRoute
  ConseilAdministrationRoute: typeof ConseilAdministrationRoute
  PartenairesRoute: typeof PartenairesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseil-administration': {
      id: '/conseil-administration'
      path: '/conseil-administration'
      fullPath: '/conseil-administration'
      preLoaderRoute: typeof ConseilAdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte': {
      id: '/charte'
      path: '/charte'
      fullPath: '/charte'
      preLoaderRoute: typeof CharteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CharteRoute: CharteRoute,
  ConseilAdministrationRoute: ConseilAdministrationRoute,
  PartenairesRoute: PartenairesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
