/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as EntrainementsRouteImport } from './routes/entrainements'
import { Route as ConseilAdministrationRouteImport } from './routes/conseil-administration'
import { Route as CollectifsRouteImport } from './routes/collectifs'
import { Route as CharteRouteImport } from './routes/charte'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrainementsRoute = EntrainementsRouteImport.update({
  id: '/entrainements',
  path: '/entrainements',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilAdministrationRoute = ConseilAdministrationRouteImport.update({
  id: '/conseil-administration',
  path: '/conseil-administration',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectifsRoute = CollectifsRouteImport.update({
  id: '/collectifs',
  path: '/collectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteRoute = CharteRouteImport.update({
  id: '/charte',
  path: '/charte',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/collectifs': typeof CollectifsRoute
  '/conseil-administration': typeof ConseilAdministrationRoute
  '/entrainements': typeof EntrainementsRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/partenaires': typeof PartenairesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/collectifs': typeof CollectifsRoute
  '/conseil-administration': typeof ConseilAdministrationRoute
  '/entrainements': typeof EntrainementsRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/partenaires': typeof PartenairesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/collectifs': typeof CollectifsRoute
  '/conseil-administration': typeof ConseilAdministrationRoute
  '/entrainements': typeof EntrainementsRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/partenaires': typeof PartenairesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/charte'
    | '/collectifs'
    | '/conseil-administration'
    | '/entrainements'
    | '/galerie'
    | '/inscription'
    | '/partenaires'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/charte'
    | '/collectifs'
    | '/conseil-administration'
    | '/entrainements'
    | '/galerie'
    | '/inscription'
    | '/partenaires'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/charte'
    | '/collectifs'
    | '/conseil-administration'
    | '/entrainements'
    | '/galerie'
    | '/inscription'
    | '/partenaires'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CharteRoute: typeof CharteRoute
  CollectifsRoute: typeof CollectifsRoute
  ConseilAdministrationRoute: typeof ConseilAdministrationRoute
  EntrainementsRoute: typeof EntrainementsRoute
  GalerieRoute: typeof GalerieRoute
  InscriptionRoute: typeof InscriptionRoute
  PartenairesRoute: typeof PartenairesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrainements': {
      id: '/entrainements'
      path: '/entrainements'
      fullPath: '/entrainements'
      preLoaderRoute: typeof EntrainementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseil-administration': {
      id: '/conseil-administration'
      path: '/conseil-administration'
      fullPath: '/conseil-administration'
      preLoaderRoute: typeof ConseilAdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectifs': {
      id: '/collectifs'
      path: '/collectifs'
      fullPath: '/collectifs'
      preLoaderRoute: typeof CollectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte': {
      id: '/charte'
      path: '/charte'
      fullPath: '/charte'
      preLoaderRoute: typeof CharteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CharteRoute: CharteRoute,
  CollectifsRoute: CollectifsRoute,
  ConseilAdministrationRoute: ConseilAdministrationRoute,
  EntrainementsRoute: EntrainementsRoute,
  GalerieRoute: GalerieRoute,
  InscriptionRoute: InscriptionRoute,
  PartenairesRoute: PartenairesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
